spring.application.name=auth-service
server.port=${SERVER_PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taxi_auth}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET:6b2b8e0ce8d1400d8a03a6e2a1df6c8dbda7e37868529e7f4f9d60b3d5adf987}
app.jwt.expiration-ms=86400000
